services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=monday
      - POSTGRES_PASSWORD=monday
      - POSTGRES_DB=monday_nails
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-monday} -d ${POSTGRES_DB:-monday_nails}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

networks:
  backend: {}

volumes:
  postgres_data: {}
